name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Prettier setup

      - name: Install prettier
        run: npm install prettier

      - name: Run Prettier check
        run: npx prettier --check .

      # Ruff setup
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Ruff
        run: pipx install ruff

      - name: Run Ruff check
        run: ruff check .
